# Generated by Django 2.2.1 on 2019-08-22 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_auto_20190822_1322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='status',
            field=models.IntegerField(choices=[(1, 'Doğru'), (0, 'Yanlış')]),
        ),
    ]
