# Generated by Django 2.2.1 on 2019-08-27 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_order_orderdetail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('New', 'New'), ('Accepted', 'Accepted'), ('Preparing', 'Preparing'), ('Onshipping', 'Onshipping'), ('Completed', 'Completed'), ('Canceled', 'Canceled')], default='New', max_length=15),
        ),
    ]
